language: groovy
jdk: oraclejdk8
sudo: false

env:
  global:
  - secure: vUAxkXES0e66PVUvPpp5rl81A+cdooe7Nc/7PjKHnrUt+jlIUoKVFAqKq4u68Yh6zNgxxtuyvKBIU9EwhTJXw742yWBEF16APUTI9tUS5CZzyZjv19mPuXjhBhJOoxlSlOdCEGcwdQ+R4+sCnJLugpvPvSWX+QMGPfuOR+dwW+DRczG4xGWc3Rg+NS5d7Fqngtrifk7bdhn3K7cWag3rDHnrqdSfGHydLW+YqFbE2AjiA3AzPIV/fUCZN9JTImneolZ5VNnkAGORbHxLeIJ7CqOcgPMhRItHSlW1kPSL2CjW614l0gDDC4vERrb+OEO/B6gNyDxbXtrcaJ+xKqbTm3+LGqY7/mxz+y1U9kdc6fCUXErsvrdnzbXvNyUlJI1Lk4JNSimOKbeOk0uXDhaKHEB6QUmvAn0L7GOwddCj5TLqNb/8yDXWnjva9f7O/LcCLjv6DnTezjRn7LrRalEK6nY3CNX/eNamyVaGJ6T++4TJmHVrnDyKolY3lRSFQvLNeKFvoqtdJILlyQa+V8v8plfcM6794LMHsFoSW46b5z4IkoZ0u5T60niWbgr8CfiFxheZVjypTgl3XfWxIDfpW4E53Reu6eWZXh1+8hp+Uzs+0X69PB9EGWz8TB024IDloPWQpCZXxcFco3pdBOwrzogse3TrTWOanaZ5pSb8J3E=
  - secure: eo0+rURfmW49Lj5T5iOX9zh0YMp9PO0kwhMncXk5TUe6dURnxHdFSN4+cweD0UNmTgyRIehRjPsZEP1fpO6N3Klg19aOxYgnqPuzn0XJ2aMAxgPwxzOxzk6Lm4c7REWan5xndL2TwnwjiwqmMnbxsHwAZ22dYq2v7uHhjRIKeM1huuYSxbAPjELq24LIZPUaermbE5H0Mnjp3L8E/99z0nXR/a82MyunhPzHiyPnlcHYEC9e9fKILRTD5YTLEDtqtX5gIZMcNIbToU4MPYfStTnI0p603fjn48M+g4Me1o/jlf5ISuzvUpkQveee/2Af6iuSJeqQEgzM4mzWAgFnnUs7Tz67hil1R6BCG33OYCP3Yj7ReaXBwQ0EB7voLvADRYQdwcyXArPm+vyfXvAaRpq2+SR3XFIINDLL5G1v3HT+Quhvz2gfEuKceA4jrFNa43+EY3AcZNzIJ10cmFxFl+kP4/c2ydGawsFfBX/AT5e2h3P9sL2EOKgVoUdptmGvAzjXf1stitHpwz5Yv23ZncoRKIS3lrlcEjvev1bgltqZ0lXjQsOVuOx5fmHZpUS1STWlS836d6Az105A7aguKbbfWwtKqxe93A3e04agv0tTKCw3w21ISb+1IpjwOab05kCJOw3wNUaoLnZo9fyT2gnq4Dvz6ed9D6jIwfywwPo=

script:
- "./gradlew clean assemble --stacktrace"

after_success:
- "./travis-publish.sh"
